### ISSUE TITLE
Packaging into the ext format will lose file_contexts configuration.

### ISSUE THREAD

**Issue by flakeforever** [affggh/NH4RomTool#1]
Hi, when I use the ext format to package, it can complete the packaging, but it doesn't import the file_contexts configuration. 
So when I unpack it after packaging, there is no file_contexts file generated, and the selinux label will be incorrect.

**Comment by affggh** [comment]
this repo is not continue anymore, you can find another rom tool, sorry...

**Comment by flakeforever** [comment]
Okay, thank you.

**Comment by affggh** [comment]
maybe you can try crd or this https://github.com/ColdWindScholar/MIO-KITCHEN-SOURCE/releases
